swagger: '2.0'
info:
  version: 1.0.0
  title: 'Projects'
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus. Phasellus pharetra nulla ac diam. Quisque semper justo at risus. Donec venenatis, turpis vel hendrerit interdum, dui ligula ultricies purus, sed posuere libero dui id orci. Nam congue, pede vitae dapibus aliquet, elit magna vulputate arcu, vel tempus metus leo non est. Etiam sit amet lectus quis est congue mollis. Phasellus congue lacus eget neque. Phasellus ornare, ante vitae consectetuer consequat, purus sapien ultricies dolor, et mollis pede metus eget nisi. Praesent sodales velit quis augue. Cras suscipit, urna at aliquam rhoncus, urna quam viverra nisi, in interdum massa nibh nec erat.
host: cdam.telecom.comarch:9000
basePath: /api/v1/
tags: [
  {name: Projects,
  description: Projects description}
  ]
consumes:
  - application/json
produces:
  - application/json
paths:
  /projects/{id}<.+>/density:
    get:
      description: 
        Gets project destination.
      operationId: projectDestination
      parameters:
        - name: id
          in: path
          description: Project id
          required: true
          type: string
      responses:
        200:
          description: Successful
          schema:
            title: Information
            type: object
            items:
              title: Account
              type: object
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error' 

  /projects/{id}<.+>:
    get:
      description: 
        Gets action by id.
      operationId: getAction
      parameters:
        - name: id
          in: path
          description: Action id
          required: true
          type: string
      responses:
        200:
          description: Successful
          schema:
            title: Information
            type: object
            items:
              title: Account
              type: object
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error' 
            
 
definitions : 
   Error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
