swagger: '2.0'
info:
  version: 1.0.0
  title: 'SparkJobs'
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus. Phasellus pharetra nulla ac diam. Quisque semper justo at risus. Donec venenatis, turpis vel hendrerit interdum, dui ligula ultricies purus, sed posuere libero dui id orci. Nam congue, pede vitae dapibus aliquet, elit magna vulputate arcu, vel tempus metus leo non est. Etiam sit amet lectus quis est congue mollis. Phasellus congue lacus eget neque. Phasellus ornare, ante vitae consectetuer consequat, purus sapien ultricies dolor, et mollis pede metus eget nisi. Praesent sodales velit quis augue. Cras suscipit, urna at aliquam rhoncus, urna quam viverra nisi, in interdum massa nibh nec erat.
host: cdam.telecom.comarch:9000
basePath: /api/v1/
tags: [
  {name: SparkJobs,
  description: SparkJobs description}
  ]
consumes:
  - application/json
produces:
  - application/json
paths:
  /sparkJobs/{jobId}/run:
    post:
      description: 
        Start process
      operationId: startProcess
      parameters:
        - name: jobId
          in: path
          description: Process id
          required: true
          type: string
      responses:
        200:
          description: Successful
          schema:
            title: Information
            type: object
            items:
              title: Account
              type: object
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error' 
            
  /sparkJobs/{applicationId}/kill:
    post:
      description: 
        Kill process
      operationId: killProcess
      parameters:
        - name: applicationId
          in: path
          description: Process id
          required: true
          type: string
      responses:
        200:
          description: Successful
          schema:
            title: Information
            type: object
            items:
              title: Account
              type: object
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error' 
            
  /sparkJobs/{jobId}/updateStatus:
    post:
      description: 
        Update Spark job status.
      operationId: updateJobStatus
      parameters:
        - name: jobId
          in: path
          description: Job id
          required: true
          type: string
      responses:
        200:
          description: Successful
          schema:
            title: Information
            type: object
            items:
              title: Account
              type: object
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error' 
            
  /sparkJobs/{jobId}/synchronizeStatus:
    post:
      description: 
        Update Spark job status.
      operationId: synchronizeStatus
      parameters:
        - name: jobId
          in: path
          description: Job id
          required: true
          type: string
      responses:
        200:
          description: Successful
          schema:
            title: Information
            type: object
            items:
              title: Account
              type: object
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error' 
            
  /sparkJobs/{applicationId}/getSparkJobStatus:
    get:
      description: 
        Get Spark job status.
      operationId: getSparkJobStatus
      parameters:
        - name: applicationId
          in: path
          description: Application id
          required: true
          type: string
      responses:
        200:
          description: Successful
          schema:
            title: Information
            type: object
            items:
              title: Account
              type: object
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
            
  /sparkJobs:
    get:
      description: 
        Get job status.
      operationId: getJobStatus
      responses:
        200:
          description: Successful
          schema:
            title: Information
            type: object
            items:
              title: Account
              type: object
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
            
            
definitions : 
   Error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
