swagger: '2.0'
info:
  version: 1.0.0
  title: '<UI>'
host: cdam.telecom.comarch:9000
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
paths:
  /ui/:
    get:
      description: 
        Gets aplication's ui
      operationId: getAppUI
      responses:
        200:
          description: Successful
          schema:
            title: Information
            type: object
            items:
              title: Account
              type: object
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error' 
            
  /ui:
    get:
      description: 
        Gets aplication's ui
      operationId: getAppUI2
      responses:
        200:
          description: Successful
          schema:
            title: Information
            type: object
            items:
              title: Account
              type: object
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error' 
            
  /ui/{file}:
    get:
      description: 
        Gets UI's file
      operationId: getUiFile
      parameters:
        - name: file
          in: path
          description: Device id
          required: true
          type: string
      responses:
        200:
          description: Successful
          schema:
            title: Information
            type: object
            items:
              title: Account
              type: object
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error' 
            
definitions : 
   Error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
