swagger: '2.0'
info:
  version: 1.0.0
  title: '<AccountsRoutes>'
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus. Phasellus pharetra nulla ac diam. Quisque semper justo at risus. Donec venenatis, turpis vel hendrerit interdum, dui ligula ultricies purus, sed posuere libero dui id orci. Nam congue, pede vitae dapibus aliquet, elit magna vulputate arcu, vel tempus metus leo non est. Etiam sit amet lectus quis est congue mollis. Phasellus congue lacus eget neque. Phasellus ornare, ante vitae consectetuer consequat, purus sapien ultricies dolor, et mollis pede metus eget nisi. Praesent sodales velit quis augue. Cras suscipit, urna at aliquam rhoncus, urna quam viverra nisi, in interdum massa nibh nec erat.
host: cdam.telecom.comarch:9000
basePath: /api/v1/
tags: [
  {name: Accounts,
  description: Accounts description}
  ]
consumes:
  - application/json
produces:
  - application/json
paths:
  /accounts:
    get:
      description: 
        Gets accounts.
      operationId: getAccounts
      responses:
        200:
          description: Successful
          schema:
            title: Account Inf
            type: object
            items:
              title: Account
              type: object
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'      
    post:
      description: Creates a new account
      operationId: createAccount
      responses:
        200:
          description: Account created successfully
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
            
  /accounts/{id}<.+>:
    get:
      description: |
        Gets accounts by id.
      operationId: getAccountById
      parameters:
        - name: id
          in: path
          description: Account's id
          required: true
          type: string
      responses:
        200:
          description: Successful
          schema:
            title: Information
            type: object
            items:
              title: Account
              type: object
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'      
              
  /accounts/{accountId}<.+>/updateCoverage: 
    post:
      description: Creates a new account
      operationId: createAccount2
      parameters:
        - name: accountId
          in: path
          description: Account's id
          required: true
          type: string
      responses:
        200:
          description: Account created successfully
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
            
definitions : 
   Error:
    type: object
    required:
      - message
    properties:
      message:
        type: string

